# Generated by Django 2.0.4 on 2020-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0006_auto_20180506_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bounds',
            field=models.IntegerField(default=100),
        ),
    ]
