# Generated by Django 2.0.4 on 2020-05-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0009_auto_20200514_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='bno',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
