# Generated by Django 2.0.4 on 2020-05-15 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0010_auto_20200515_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cno',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
